@startuml

title __LAB's Class Diagram__\n

  package server {
    class Auth {
    }
  }
  

  package client {
    class BackTable {
    }
  }
  

  package shared {
    class CSVUtils {
    }
  }
  

  package client {
    class Client {
    }
  }
  

  package shared {
    class Command {
    }
  }
  

  package server {
    class CommandHandler {
    }
  }
  

  package shared {
    class Console {
    }
  }
  

  package shared {
    class ConsoleClient {
    }
  }
  

  package shared {
    class CustomCommands {
    }
  }
  

  package server {
    class DataBaseConnection {
    }
  }
  

  package shared {
    class Disability {
    }
  }
  

  package shared {
    class FileHandler {
    }
  }
  

  package shared {
    abstract class God {
    }
  }
  

  package shared {
    class Human {
    }
  }
  

  package server {
    class JavaMail {
    }
  }
  

  package shared {
    class Localisation {
    }
  }
  

  package client {
    class Login {
    }
  }
  

  package client {
    class MainUI {
    }
  }
  

  package client {
    package client.Localisation {
      class MyResources_ch {
      }
    }
  }
  

  package client {
    package client.Localisation {
      class MyResources_en {
      }
    }
  }
  

  package client {
    package client.Localisation {
      class MyResources_pl {
      }
    }
  }
  

  package client {
    package client.Localisation {
      class MyResources_ru {
      }
    }
  }
  

  package shared {
    class Response {
    }
  }
  

  package server {
    class Server {
    }
  }
  

  package client {
    package client.Controllers {
      class SkeletonEdit {
      }
    }
  }
  

  package client {
    package client.Controllers {
      class SkeletonLogin {
      }
    }
  }
  

  package client {
    package client.Controllers {
      class SkeletonMain {
      }
    }
  }
  

  package client {
    package client.Controllers {
      class SkeletonRegister {
      }
    }
  }
  

  package shared {
    class Skill {
    }
  }
  

  package shared {
    class Temp {
    }
  }
  

  package shared {
    class TestMain {
    }
  }
  

  package server {
    class User {
    }
  }
  

  Auth -up-|> Authenticator
  BackTable -up-|> TimerTask
  Command -up-|> Serializable
  CommandHandler o-- Command : command
  CommandHandler o-- DataBaseConnection : db
  Console o-- CustomCommands : customCommands
  Disability -up-|> Serializable
  God -up-|> Serializable
  Human -up-|> Serializable
  Human -up-|> Comparable
  Human -up-|> God
  Login -up-|> Application
  MainUI -up-|> Application
  MyResources_ch -up-|> ListResourceBundle
  MyResources_en -up-|> ListResourceBundle
  MyResources_pl -up-|> ListResourceBundle
  MyResources_ru -up-|> ListResourceBundle
  Response -up-|> Serializable
  Server o-- DataBaseConnection : db
  SkeletonMain -up-|> Initializable
  SkeletonMain o-- Human : selected
  Skill -up-|> Serializable
  Temp -up-|> Serializable
  Temp o-- Skill : skill


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
