@startuml

title __LAB's Class Diagram__\n

  package server {
    class Auth {
    }
  }
  

  package shared {
    class CSVUtils {
    }
  }
  

  package client {
    class Client {
    }
  }
  

  package shared {
    class Command {
    }
  }
  

  package server {
    class CommandHandler {
    }
  }
  

  package shared {
    class Console {
    }
  }
  

  package shared {
    class ConsoleClient {
    }
  }
  

  package shared {
    class CustomCommands {
    }
  }
  

  package server {
    class DataBaseConnection {
    }
  }
  

  package shared {
    class Disability {
    }
  }
  

  package shared {
    class FileHandler {
    }
  }
  

  package shared {
    abstract class God {
    }
  }
  

  package shared {
    class Human {
    }
  }
  

  package server {
    class JavaMail {
    }
  }
  

  package shared {
    class Main {
    }
  }
  

  package shared {
    class Response {
    }
  }
  

  package server {
    class Server {
    }
  }
  

  package shared {
    class Skill {
    }
  }
  

  package shared {
    class Temp {
    }
  }
  

  Auth -up-|> Authenticator
  Command -up-|> Serializable
  Console o-- CustomCommands : customCommands
  DataBaseConnection o-- CommandHandler : command
  Disability -up-|> Serializable
  God -up-|> Serializable
  Human -up-|> Serializable
  Human -up-|> Comparable
  Human -up-|> God
  Response -up-|> Serializable
  Server o-- DataBaseConnection : db
  Skill -up-|> Serializable
  Temp -up-|> Serializable
  Temp o-- Skill : skill


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
