package client.Localisation;

import java.util.ListResourceBundle;

public class MyResources_en extends ListResourceBundle {

    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"register", "Registration"},
                {"login", "Login"},
                {"clear", "Clear"},
                {"main", "Main UI"},
                {"email", "Email"},
                {"serverConnection", "Server Connection"},
                {"helpText", "An application for organising your slavery business.\nCreator: Ivan Bratchikov"},
                {"disconnected", "Disconnected from the server.\nTry again later!"},
                {"collectionInfo", "Collection of Vector type. Contains objects of human type."},
                {"submit", "Submit"},
                {"sheerVoid", "The fields command, name and age can't be void. (Size can't be 0) \nMake sure they're set."},
                {"coordinatesVoid", "You didn't provide any coordinates. Thus the default preset was used!\nX = 0, Y = 0."},
                {"yMissing", "You didn't provide Y coordinates. Thus the default preset was used!\nY = 0."},
                {"xMissing", "You didn't provide X coordinates. Thus the default preset was used!\nX = 0."},
                {"skillNameMissing", "You can't provide skill info and don't provide skill name\nTry again!"},
                {"nicknameAndEmailVoid", "Make sure nickname and email fields are filled!"},
                {"nicknameAndPasswordVoid", "Make sure nickname and password fields are filled!"},
                {"cantLoadMainUI", "Can't load the main UI!\n"},
                {"objects", "Objects"},
                {"sorry", "Sorry"},
                {"why", "Why?!"},
                {"noResponse", "Can get the response!\n"},
                {"message","Message"},
                {"warning", "Warning"},
                {"nickname", "Nickname"},
                {"password", "Password"},
                {"language", "Language"},
                {"help", "Help"},
                {"button", "Button"},
                {"about", "About"},
                {"table", "Table"},
                {"theme", "Theme"},
                {"logout", "Logout"},
                {"info", "Info"},
                {"humans", "Humans"},
                {"desk", "Remote Control"},
                {"action", "Action"},
                {"command", "Command"},
                {"add","Add"},
                {"remove", "Remove"},
                {"remove_greater", "Remove Greater"},
                {"remove_lower", "Remove Lower"},
                {"add_if_min", "Add If Min"},
                {"human", "Human"},
                {"general", "General"},
                {"location", "Location"},
                {"skill", "Skill"},
                {"size", "Size"},
                {"pickedSize", "Picked Size: "},
                {"name", "Name"},
                {"age", "Age"},
                {"xCoordinate", "X Coordinate = 0"},
                {"yCoordinate", "Y Coordinate = 0"},
                {"info", "Info"},
                {"lastCommand", "Last Command:"},
                {"lastHuman", "Last Human:"},
                {"dont", "Don't press it!"},
                {"notANumber", "Entered field is not a number!"},
                {"date", "Date"},
                {"update", "Update"},
                {"notSelectHuman", "You didn't select a human to modify!"},
                {"mode", "Mode"},
                {"canvas", "Canvas"},
                {"filter", "Filter"},
                {"showTable", "You didn't switched mode to Table!"},
                {"registerFirst", "You need to register first!"},
                {"wrongPass", "Wrong Password!"},
                {"userNotAuth", "User is not authorized"},
                {"added", "A human %s was successfully added."},
                {"alreadyExists", "Collection already stores this object."},
                {"nameIsntTheSmallest", "%s's name isn't the smallest: Can't add to a collection!"},
                {"deleted", "A human %s has been deleted"},
                {"cantDelete", "There's no such object in the collection. Try adding instead." +
                        "\nPerhaps, you don't have rights to delete it!"},
                {"deletedN", "Deleted %s objects."},
                {"updated", "Human %s has been updated."},
                {"cantUpdate", "Human %s belongs to other user.\nCan't update!"},
                {"emailSent", "Email registration is approved!"},
                {"userRegistered", "You've already registered!"},
                {"cantRegister", "Can't register you"}
        };
    }
}